name: Deploy React Projects to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      # Build project1
      - name: Install and build basic-react-app
        working-directory: ./basic-react-app
        run: |
          npm ci
          npm run build

      # Build project2
      - name: Install and build Lottery-Ticket
        working-directory: ./Lottery-Ticket
        run: |
          npm ci
          npm run build

      # Create one folder containing all projects
      - name: Create Pages directory
        run: |
          mkdir -p pages/basic-react-app
          mkdir -p pages/Lottery-Ticket

      # Copy each project's dist into its own folder
      - name: Copy project builds
        run: |
          cp -r project1/dist/. pages/basic-react-app/
          cp -r project2/dist/. pages/Lottery-Ticket/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
