name: Deploy React Projects

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build basic-react-app
        working-directory: ./basic-react-app
        run: |
          npm ci
          npm run build

      - name: Build Lottery-Ticket
        working-directory: ./Lottery-Ticket
        run: |
          npm ci
          npm run build

      - name: Prepare Pages
        run: |
          mkdir -p pages/basic-react-app
          mkdir -p pages/Lottery-Ticket

          cp -r project1/dist/. pages/basic-react-app/
          cp -r project2/dist/. pages/Lottery-Ticket/

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
